name: Download Azure Web Logs
on:
  workflow_dispatch:
    inputs:
      resource-group-name:
        default: 'dev-onyx-sandbox-v1-eun-layer3-rg'
        description: 'Name of the resource group the webapp is in'
        required: true
      webapp-name:
        default: 'dev-onyx-sandbox-v1-eun-layer3-app'
        description: 'Name of the webapp'
        required: true
      environment:
        description: 'Environment: deveun or prodeun'
        default: deveun
        type: environment
        required: true 

jobs:
  get-the-logs:
    runs-on: ubuntu-latest
    name: Get the application logs
    environment:
      name: ${{ github.event.inputs.environment}}

    steps:
      - name: Set up secret file
        env:
          SECRET: ${{ secrets.SECRET  }}
        run: |
          echo $SECRET >> secrets.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v3
